<?php
/**
 * Created by PhpStorm.
 * User: noicfank
 * Date: 2017/11/18
 * Time: 13:46
 */

namespace frontend\controllers\base;


use yii\web\Controller;

class BaseController extends Controller
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}