<?php
/**
 * Created by PhpStorm.
 * User: noicfank
 * Date: 2017/11/15
 * Time: 14:18
 * 这就是所有web api controller的基类
 */
namespace backend\modules\api\v1\controllers\base;

use yii\filters\Cors;
use yii\helpers\ArrayHelper;
use yii\rest\ActiveController;

class BaseController extends ActiveController
{
    //在所有Action之前调用
    public function beforeAction($action)
    {
        //CORS中的option问题
        $request = \Yii::$app->request;
        if($request->isOptions){
            $res = \Yii::$app->response;
            return $res;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return ArrayHelper::merge([
            [
                'class' => Cors::className(),
                'cors' => [
                    'Origin' => ['*'],
                    'Access-Control-Allow-Origin' => ['*'],
                    'Access-Control-Request-Method' => ['*'],
                    'Access-Control-Request-Headers' => ['*'],
                    'Access-Control-Allow-Credentials' => true,
                    'Access-Control-Max-Age' => 86400,
                ]
            ],
        ], parent::behaviors());
    }

}